### ISSUE TITLE
CSS solution

### ISSUE THREAD

**Issue by svnpenn** [DennisSnijder/MakeGithubGreatAgain#27]
Since @mdo has completely [lost the plot][q]:

> For now! Not trying to be a jerk, but that extra class will be going away
> soon. Just how we shipped v1 of it.

It might be a good idea to implement a CSS solution, as the JavaScript solution
is likely to break. Here is one I came up with:

http://github.com/svnpenn/dotfiles/blob/cf47bf9/stylish/github.css#L2-L32

[q]://twitter.com/mdo/status/830149416556191744

**Comment by adamschwartz** [comment]
I believe that’s missing a few things, e.g. input placeholder colors:

```CSS
.header-dark .header {
  color: #333;
  background-color: #f5f5f5;
  border-bottom: 1px solid #e5e5e5;
}

.header-dark .read-only-mode-banner {
  background-color: #f8e45f;
  border-bottom-color: #f6dc2e;
}

.header-dark .header-logo-invertocat, .header-dark .header-logo-wordmark {
  color: #555;
}

.header-dark .header-logo-invertocat:hover, .header-dark .header-logo-wordmark:hover {
  color: #4078c0;
}

.header-dark .notification-indicator .mail-status {
  color: #fff;
  background-image: -webkit-linear-gradient(#1cafff, #0086ce);
  background-image: linear-gradient(#1cafff, #0086ce);
  border: 2px solid #f3f3f3;
}

.header-dark .notification-indicator:hover .mail-status {
  background-color: #4078c0;
}

.header-dark .header-search-scope {
  color: #767676;
  border-right: 1px solid #eee;
}

.header-dark .scoped-search .form-control.focus .header-search-scope {
  color: #4078c0;
  background-color: #edf2f9;
  border-color: #c6d7ec;
}

.header-dark .header-nav-link {
  color: #555;
}

.header-dark .header-nav-link:hover, .header-dark .header-nav-link:focus {
  color: #4078c0;
}

.header-dark .header-nav-link:hover .dropdown-caret, .header-dark .header-nav-link:focus .dropdown-caret {
  border-top-color: #4078c0;
}

.header-dark .header-search {
  font-size: 14px;
}

.header-dark .header-search-wrapper {
  background: #fff;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);
  border: 1px solid #ddd;
  font-size: 14px;
  min-height: 0;
}

.header-dark .header-search-scope {
  font-size: 12px;
  line-height: inherit;
  min-height: 0;
}

.header-dark .header-search-input {
  min-height: 26px;
}

.header-dark .header-search-input::-webkit-input-placeholder {
  color: rgba(0, 0, 0, .5);
}

.header-dark .header-search-input::placeholder {
  color: rgba(0, 0, 0, .5);
}
```

Once they drop `.header-dark` use this:

```CSS
.header {
  color: #333;
  background-color: #f5f5f5;
  border-bottom: 1px solid #e5e5e5;
}

.read-only-mode-banner {
  background-color: #f8e45f;
  border-bottom-color: #f6dc2e;
}

.header-logo-invertocat, .header-logo-wordmark {
  color: #555;
}

.header-logo-invertocat:hover, .header-logo-wordmark:hover {
  color: #4078c0;
}

.notification-indicator .mail-status {
  color: #fff;
  background-image: -webkit-linear-gradient(#1cafff, #0086ce);
  background-image: linear-gradient(#1cafff, #0086ce);
  border: 2px solid #f3f3f3;
}

.notification-indicator:hover .mail-status {
  background-color: #4078c0;
}

.header-search-scope {
  color: #767676;
  border-right: 1px solid #eee;
}

.scoped-search .form-control.focus .header-search-scope {
  color: #4078c0;
  background-color: #edf2f9;
  border-color: #c6d7ec;
}

.header-nav-link {
  color: #555;
}

.header-nav-link:hover, .header-nav-link:focus {
  color: #4078c0;
}

.header-nav-link:hover .dropdown-caret, .header-nav-link:focus .dropdown-caret {
  border-top-color: #4078c0;
}

.header-search {
  font-size: 14px;
}

.header-search-wrapper {
  background: #fff;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);
  border: 1px solid #ddd;
  font-size: 14px;
  min-height: 0;
}

.header-search-scope {
  font-size: 12px;
  line-height: inherit;
  min-height: 0;
}

.header-search-input {
  min-height: 26px;
}

.header-search-input::-webkit-input-placeholder {
  color: rgba(0, 0, 0, .5);
}

.header-search-input::placeholder {
  color: rgba(0, 0, 0, .5);
}
```
