### ISSUE TITLE
New CSS overwriting for both Safari and Firefox extension

### ISSUE THREAD

**Issue by DennisSnijder** [DennisSnijder/MakeGithubGreatAgain#32]
As Github changed the "dark-header" class.
The Firefox and Safari extensions are broken.

This needs to be fixed.

**Comment by xeno-by** [comment]
Doesn't work for me on Chrome either.

**Comment by DennisSnijder** [comment]
@xeno-by Try the new version on the master branch.
Update will be published ASAP to the chrome extension store.

**Comment by xeno-by** [comment]
@DennisSnijder I can confirm this working for me. Thank you!

**Comment by DennisSnijder** [comment]
@xeno-by Thanks for testing 👍
Updated it couple if minutes ago.

**Comment by delneg** [comment]
Confirmed, updated from master and it working now.
That black glow of death freaked me out for several minutes though.

**Comment by fabricionaweb** [comment]
@DennisSnijder, I was preparing a PR when you updated hehe
That would be my CSS, take some improvements.

```css
/* A higher specification avoids `!important` */
.header.great-header {
    border-bottom: 1px solid #E5E5E5;
    background-color: #F5F5F5;
    height: 54px; /* prevents reflow */
}

.header.great-header .header-logo-invertocat,
.header.great-header .header-logo-wordmark {
    color: #555;
}

.header.great-header .header-logo-invertocat:hover,
.header.great-header .header-logo-wordmark:hover {
    color: #4078C0;
}

.header.great-header .header-nav-link {
    color: #555;
}

.header.great-header .header-nav-link:hover,
.header.great-header .header-nav-link:focus {
    color: #4078c0;
}

.header.great-header .header-nav-link:hover .dropdown-caret,
.header.great-header .header-nav-link:focus .dropdown-caret {
    border-top-color: #4078c0;
}

.header.great-header .notification-indicator .mail-status {
    border-color: #f3f3f3;
}

.header.great-header .header-search-scope {
    color: #767676;
    border-right-color: #EEE;
}

.header.great-header .header-search-wrapper {
    color: #333;
    background-color: #FFF;
    border: 1px solid #DDD;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.075);
}

.header.great-header .header-search-wrapper.focus {
    background-color: #FFF;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.075), 
                0 0 5px rgba(81, 167, 232, 0.5);
    border-color: #51A7E8;
}

.header.great-header .header-search-wrapper.focus .header-search-scope {
    color: #4078C0;
    background-color: #EDF2F9;
    border-right-color: #C6D7EC;
}

.header.great-header .header-search-input {
    color: #333;
}

.header.great-header .header-search-input::-webkit-input-placeholder {
    color: #999;
}
.header.great-header .header-search-input:placeholder {
    color: #999;
}

.header.great-header .header-search-input::-moz-placeholder {
    color: #999;
}
.header.great-header .header-search-input:-moz-placeholder {
    color: #999;
}
```
