### ISSUE TITLE
The header will firstly become black and then turn to white.

### ISSUE THREAD

**Issue by TheodoreKrypton** [DennisSnijder/MakeGithubGreatAgain#48]
It will be better if the original css file can be blocked.

**Comment by getsmp** [comment]
Look at #4

**Comment by babobski** [comment]
@TheodoreKrypton or you can use a different approach.
For Firefox, Chrome, Safari and Opera there is a stylish addon available, this addon you can write custom css for any web-address. If you use this approach you will not have any flashing.
Made a [Gist](https://gist.github.com/babobski/41b29114a3c774bd018f75bd4fffc872) that will revert the black bar, you can tweak it to you're likings.

The stylish addons:
[FireFox](https://addons.mozilla.org/en-US/firefox/addon/stylish/?src=external-userstyleshome)
[Chrome](https://chrome.google.com/webstore/detail/fjnbnpbmkenffdnngjfgmeleoegfcffe)
[Safari](http://sobolev.us/stylish/)
[Opera](https://addons.opera.com/extensions/details/stylish/)

**Comment by nhooyr** [comment]
@babobski with that css, the links are not highlighted when you over them. I tried to add some css for styling the links 

I'm using the following css (I took it from this repo and replaced all `.great-header` selectors with `.header`

```
.header.header {
    color: #333;
    background-color: #f5f5f5;
    border-bottom: 1px solid #e5e5e5
}

.header .header-search-scope {
   color: rgb(64, 120, 192);
   background-color: rgb(237, 242, 249);
   border-color: rgb(198, 215, 236);
}

.header .read-only-mode-banner {
    background-color: #f8e45f;
    border-bottom-color: #f6dc2e
}

.header .header-logo-invertocat, .header .header-logo-wordmark {
    color: #555
}

.header .notification-indicator .mail-status {
    color: #fff;
    background-image: -webkit-linear-gradient(#1cafff, #0086ce);
    background-image: linear-gradient(#1cafff, #0086ce);
    border: 2px solid #f3f3f3
}

.header .notification-indicator:hover .mail-status {
    background-color: #4078c0
}

.header .header-search-scope {
    font-size: inherit;
    color: #767676 !important;
    border-right: 1px solid #eee !important;
}

.header .scoped-search .form-control.focus .header-search-scope {
    color: #4078c0;
    background-color: #edf2f9;
    border-color: #c6d7ec
}

.header .header-nav-link {
    color: #555
}
.header .header-logo-invertocat:hover, .header .header-logo-wordmark:hover,
.header .header-nav-link:hover, .header .header-nav-link:focus {
    color: #4078c0
}

.header .header-nav-link:hover .dropdown-caret, .header .header-nav-link:focus .dropdown-caret {
    border-top-color: #4078c0
}

.header .header-search {
    font-size: 14px
}

.header .header-search-wrapper {
    background: #fff;
    box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);
    border: 1px solid #ddd;
    font-size: 14px;
    min-height: 0;
}

.header .header-search-wrapper.focus {
    background: #fff;
    border-color: #51a7e8;
    outline: none;
    color: inherit;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 5px rgba(81, 167, 232, .5);
}

.header .header-search-scope {
    font-size: 12px;
    line-height: inherit;
    min-height: 0;
}

.header .header-search-input {
    min-height: 26px;
}

.header .header-search-input::-webkit-input-placeholder,
.header .header-search-input::placeholder {
    color: rgba(0,0,0,.5)
}

.header .form-control {
    color: #333 !important;
    background-color: #fff !important;
}

.header *::-webkit-input-placeholder {
    color: #767676 !important;
}
.header *:-moz-placeholder {
    /* FF 4-18 */
    color: #767676 !important;
}
.header *::-moz-placeholder {
    /* FF 19+ */
    color: #767676 !important;
}
.header *:-ms-input-placeholder {
    /* IE 10+ */
    color: #767676 !important;
}
```

**Comment by nhooyr** [comment]
@babobski with that css, some links aren't highlighted properly.

![screen shot 2017-02-22 at 3 19 45 am](https://cloud.githubusercontent.com/assets/10180857/23202841/f04a548c-f8ad-11e6-96f6-eeb5fb79b234.png)

I'm using the following css (I took it from this repo and replaced all `.great-header` selectors with `.header`

```css
.header.header {
    color: #333;
    background-color: #f5f5f5;
    border-bottom: 1px solid #e5e5e5
}

.header .header-search-scope {
   color: rgb(64, 120, 192);
   background-color: rgb(237, 242, 249);
   border-color: rgb(198, 215, 236);
}

.header .read-only-mode-banner {
    background-color: #f8e45f;
    border-bottom-color: #f6dc2e
}

.header .header-logo-invertocat, .header .header-logo-wordmark {
    color: #555
}

.header .notification-indicator .mail-status {
    color: #fff;
    background-image: -webkit-linear-gradient(#1cafff, #0086ce);
    background-image: linear-gradient(#1cafff, #0086ce);
    border: 2px solid #f3f3f3
}

.header .notification-indicator:hover .mail-status {
    background-color: #4078c0
}

.header .header-search-scope {
    font-size: inherit;
    color: #767676 !important;
    border-right: 1px solid #eee !important;
}

.header .scoped-search .form-control.focus .header-search-scope {
    color: #4078c0;
    background-color: #edf2f9;
    border-color: #c6d7ec
}

.header .header-nav-link {
    color: #555
}
.header .header-logo-invertocat:hover, .header .header-logo-wordmark:hover,
.header .header-nav-link:hover, .header .header-nav-link:focus {
    color: #4078c0
}

.header .header-nav-link:hover .dropdown-caret, .header .header-nav-link:focus .dropdown-caret {
    border-top-color: #4078c0
}

.header .header-search {
    font-size: 14px
}

.header .header-search-wrapper {
    background: #fff;
    box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);
    border: 1px solid #ddd;
    font-size: 14px;
    min-height: 0;
}

.header .header-search-wrapper.focus {
    background: #fff;
    border-color: #51a7e8;
    outline: none;
    color: inherit;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 5px rgba(81, 167, 232, .5);
}

.header .header-search-scope {
    font-size: 12px;
    line-height: inherit;
    min-height: 0;
}

.header .header-search-input {
    min-height: 26px;
}

.header .header-search-input::-webkit-input-placeholder,
.header .header-search-input::placeholder {
    color: rgba(0,0,0,.5)
}

.header .form-control {
    color: #333 !important;
    background-color: #fff !important;
}

.header *::-webkit-input-placeholder {
    color: #767676 !important;
}
.header *:-moz-placeholder {
    /* FF 4-18 */
    color: #767676 !important;
}
.header *::-moz-placeholder {
    /* FF 19+ */
    color: #767676 !important;
}
.header *:-ms-input-placeholder {
    /* IE 10+ */
    color: #767676 !important;
}
```
